import { revalidatePath } from "next/cache";

// The public pages are statically rendered. After a change visitors can see
// (a publish, an unpublish, a new order, a slug or visibility change) every
// page a published change can reach is regenerated on its next request:
// Home, Art Works, every Project Detail page (their next-project links follow
// the order) and the sitemap. About and Contact are content files and never
// change at run time.
//
// Not the whole tree: revalidating the root layout also invalidates the
// prerendered 404, which is then regenerated by whichever missing address is
// requested next and keeps that address's navigation state — a 404 under
// /works would mark "Works" as the current page on every later 404.
export function revalidatePublicSite() {
  revalidatePath("/");
  revalidatePath("/works");
  // A dynamic route is named by its file path, route group included.
  revalidatePath("/(project)/works/[slug]", "page");
  revalidatePath("/sitemap.xml");
}
